org.gradle.jvmargs=-Xmx2G

# BTA
bta_version=7.3_04
bta_channel=release

# Loader
loader_version=0.15.6-bta.7

# HalpLibe
mod_menu_version=3.0.0
halplibe_version=5.2.4
catalyst_core_version=2.1.0

# Scalable Cat's Force Fabric
scf_version=3.1.6
scala_version=3.3.4
cats_version=2.12.1-kotori

# Mod
mod_version=0.0.1
mod_group=com.github.gabryx64
mod_name=chuted

